--[[
	Displays the altitude and speed and darkens the player's screen based on altitude
--]]

--[[
	MIT License
	Copyright (c) 2019 Anthony O"Brien (Sublivion)
	
	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
--]]

-- Services
Players = game:GetService("Players")
RunService = game:GetService("RunService")

--[[
	Creates the ScreenGui to display the speed and altitude
	
	Generated by a plugin: https://www.roblox.com/library/313196955/
--]]
function createGui()
	local NewGuiPart1 = Instance.new("ScreenGui")
	NewGuiPart1.Name = "RocketSys"
	local NewGuiPart2 = Instance.new("Frame")
	NewGuiPart2.BackgroundColor3 = Color3.new(0.152941, 0.160784, 0.188235)
	NewGuiPart2.BackgroundTransparency = 0.10000000149012
	NewGuiPart2.BorderSizePixel = 0
	NewGuiPart2.Name = "UiContainer"
	NewGuiPart2.Position = UDim2.new(0, 0, 1, 0)
	NewGuiPart2.Size = UDim2.new(0.150000006, 0, 0.100000001, 0)
	NewGuiPart2.Parent = NewGuiPart1
	local NewGuiPart3 = Instance.new("Frame")
	NewGuiPart3.BackgroundTransparency = 1
	NewGuiPart3.Name = "ListContainer"
	NewGuiPart3.Size = UDim2.new(1, 0, 1, 0)
	NewGuiPart3.Parent = NewGuiPart2
	local NewGuiPart4 = Instance.new("TextLabel")
	NewGuiPart4.BackgroundColor3 = Color3.new(0.152941, 0.160784, 0.188235)
	NewGuiPart4.BackgroundTransparency = 1
	NewGuiPart4.BorderSizePixel = 0
	NewGuiPart4.Position = UDim2.new(0, 0, 1, 0)
	NewGuiPart4.Size = UDim2.new(1, 0, 0.5, 0)
	NewGuiPart4.Font = Enum.Font.GothamSemibold
	NewGuiPart4.FontSize = Enum.FontSize.Size18
	NewGuiPart4.Text = "250 KM/H"
	NewGuiPart4.TextColor3 = Color3.new(0.980392, 0.980392, 0.980392)
	NewGuiPart4.TextWrapped = true
	NewGuiPart4.Parent = NewGuiPart3
	local NewGuiPart5 = Instance.new("TextLabel")
	NewGuiPart5.BackgroundColor3 = Color3.new(0.152941, 0.160784, 0.188235)
	NewGuiPart5.BackgroundTransparency = 1
	NewGuiPart5.BorderSizePixel = 0
	NewGuiPart5.Position = UDim2.new(0, 0, 1, 0)
	NewGuiPart5.Size = UDim2.new(1, 0, 0.5, 0)
	NewGuiPart5.Font = Enum.Font.GothamSemibold
	NewGuiPart5.FontSize = Enum.FontSize.Size18
	NewGuiPart5.Text = "10 KM"
	NewGuiPart5.TextColor3 = Color3.new(0.980392, 0.980392, 0.980392)
	NewGuiPart5.TextWrapped = true
	NewGuiPart5.Parent = NewGuiPart3
	local NewGuiPart6 = Instance.new("TextLabel")
	NewGuiPart6.BackgroundColor3 = Color3.new(0.152941, 0.160784, 0.188235)
	NewGuiPart6.BorderSizePixel = 0
	NewGuiPart6.Name = "Header"
	NewGuiPart6.Position = UDim2.new(0, 0, -0.300000012, 0)
	NewGuiPart6.Size = UDim2.new(1, 0, 0.300000012, 0)
	NewGuiPart6.Font = Enum.Font.GothamBlack
	NewGuiPart6.FontSize = Enum.FontSize.Size14
	NewGuiPart6.Text = "ROCKETSYS III"
	NewGuiPart6.TextColor3 = Color3.new(1, 1, 1)
	NewGuiPart6.Parent = NewGuiPart2
	return NewGuiPart1
end

-- Initialisation
local player = Players.LocalPlayer
local gui = createGui()
gui.Parent = player.PlayerGui

-- Game loop
RunService.Heartbeat:Connect(function()
	
end)
